export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_EVENTS_COMPLETED = "FETCH_EVENTS_COMPLETED";
export const FETCH_EVENTS_ERROR = "FETCH_EVENTS_ERROR";

export const LOADING_FINISHED = "LOADING_FINISHED";
export const LOADING_STARTED = "LOADING_STARTED";

export const PAGINATION_STARTED = "PAGINATION_STARTED";
export const PAGINATION_COMPLETED = "PAGINATION_COMPLETED";
